version: "3"

services:

  mysql_curso:

    container_name: mysql_curso

    hostname: mysql_curso

    image: mysql

    command:

      - --default-authentication-plugin=mysql_native_password

      - --character-set-server=utf8mb4

      - --collation-server=utf8mb4_unicode_ci

      - --innodb_force_recovery=0


    ports:

      - 3306:3306

    environment:

      MYSQL_ROOT_PASSWORD: teste123

      MYSQL_DB: base_de_dados

      MYSQL_USER: usuario

      MYSQL_PASSWORD: teste123

      TZ: America/Sao_Paulo
